### ISSUE TITLE
Missing Inline Variable refactoring

### ISSUE THREAD

**Issue by onewhl** [tsantalis/RefactoringMiner#154]
Hello! I noticed that RefactoringMiner doesn't detect Inline Variable refactoring at the following code changes:

Before:
```
public String getName() {
        String name = "A";
        return name;
}
```

After:   
```
public String getName() {
        return "A";
 }   
```

RefactoringMiner version: **2.0.3**

**Comment by tsantalis** [comment]
In this case `String name = "A";` is matched with `return "A";` instead of
`return name;` -> `return "A";` +
Inline Variable
`String name = "A";`

A similar scenario for **Extract Variable** holds in case
[return "A";](https://github.com/javaparser/javaparser/commit/427dd53b9ebedcb0bdb687007eb0faf2de734df4#diff-d4545a64b742a6d7b072135d10643c1d309ecaa62daa9450ba05dc68985543aaR477)
where
`final VariableDeclarator variableDeclarator = (VariableDeclarator)type.getParentNode().get();` is matched with
`Node parent = type.getParentNode().get();`
instead of
`final VariableDeclarator variableDeclarator = (VariableDeclarator)type.getParentNode().get();` ->
`final VariableDeclarator variableDeclarator = (VariableDeclarator) parent;` +
Extract Variable
`Node parent = type.getParentNode().get();`

**Comment by tsantalis** [comment]
@onewhl 
This old issue is fixed.

![Screenshot from 2023-08-01 17-01-37](https://github.com/tsantalis/RefactoringMiner/assets/1483516/f03e44d4-7701-4d18-9bfb-ffe8cbba62e0)


![Screenshot from 2023-08-01 08-22-07](https://github.com/tsantalis/RefactoringMiner/assets/1483516/6d58bf3c-6620-4c9c-807c-5ac9f11fa215)
