### ISSUE TITLE
UMLType Fully Qualified Name

### ISSUE THREAD

**Issue by Ahmadreza-SY** [tsantalis/RefactoringMiner#298]
Hi,
I am trying to get the fully qualified class name of the type of method parameters. I first get the parameter type list from a given `UMLOperation`, then I call `getClassType()` or `toQualifiedString()` on each parameter which is a `UMLType`. However, I do not get the fully qualified name of the class name.

For example, for a method with a `String` parameter, I need to get `"java.lang.String"` as the fully qualified name, but the functions I mentioned above return `"String"`.

Is there a way to get the fully qualified name?

Thank you

**Comment by tsantalis** [comment]
Hi @Ahmadreza-SY 
Thank you for your question.

RefactoringMiner does not perform binding resolution in order to recover fully qualified names for the referenced types.
`toQualifiedString()` will return a qualified type only if the type is qualified directly in the source code.

There is another project based on RefactoringMiner that qualifies the types for type-related refactorings.
https://github.com/ameyaKetkar/TypeChangeMiner
You can ask @ameyaKetkar for more details about this project.

Let me know if you have any further questions.

**Comment by Ahmadreza-SY** [comment]
> Hi @Ahmadreza-SY Thank you for your question.
> 
> RefactoringMiner does not perform binding resolution in order to recover fully qualified names for the referenced types. `toQualifiedString()` will return a qualified type only if the type is qualified directly in the source code.
> 
> There is another project based on RefactoringMiner that qualifies the types for type-related refactorings. https://github.com/ameyaKetkar/TypeChangeMiner You can ask @ameyaKetkar for more details about this project.
> 
> Let me know if you have any further questions.

The project is indeed helpful. Thank you.
