### ISSUE TITLE
Method with identical names inside interface not reported as mapped while the signature has been changed

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#423]
https://github.com/scobal/seyren/commit/5fb36a321af7df470d4c845cb18da8f85be31c38
File: [EmailHelper.java](https://github.com/scobal/seyren/commit/5fb36a321af7df470d4c845cb18da8f85be31c38#diff-3747147124805732fbfcb9e4455d5047dcca557c4bdb74636e4a26fde35f55bb)

**Problem**: The signature of the method has been changed but the method is reported as deleted and added. 

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28820932/227141665-aa499637-5d21-4669-8808-b49d170804e4.png">

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/28820932/227141334-4d0e4426-119e-498f-91f7-51a7ef878c8b.png">

**Comment by tsantalis** [comment]
RefactoringMiner can infer changes in interface methods, based on the changes in methods overriding the interface methods in subclasses.

In this commit, there is a class named `VelocityEmailHelper`, which implements the `EmailHelper` interface, but we could not match the method `createSubject()`, because its body changed significantly. 
![Screenshot from 2023-04-21 14-28-55](https://user-images.githubusercontent.com/1483516/233709717-4ee1c137-5988-4b2b-ba2c-8c8a40e6cb39.png)

One last resort we have is to infer method declaration mappings based on method call mappings.

For example, in class `EmailNotificationService` there is a method call to `createSubject()` with two added arguments.

![Screenshot from 2023-04-21 14-34-24](https://user-images.githubusercontent.com/1483516/233710539-b46683ff-7c60-4873-97e2-c294241075a6.png)

**Comment by tsantalis** [comment]
@pouryafard75 
This issue has been fixed. We can infer method declaration mappings from method invocation replacements found in mapped statements (in the same or other files).
