### ISSUE TITLE
Add support to analyze a particular type of refactoring

### ISSUE THREAD

**Issue by IP1102** [tsantalis/RefactoringMiner#455]
As far as I know, the current version looks for all types of refactorings in all or a range of commits. Let's say I want to only identify _extract method_ refactorings in all commits of a project. Can a functionality be implemented where by passing only the name of the refactoring as a command line argument, the tool will only look for the said refactoring in the commits? Something like the following -

`RefactoringMiner -a <git-repo-folder> <branch> --refactoring-name extract-method -json <path-to-json-file>`

**Comment by tsantalis** [comment]
Duplicate with issue  #244


You can comment out the refactoring types you don't want in
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/api/RefactoringType.java#L116-L216

The refactoring types to be considered is set in the GitHistoryRefactoringMinerImpl constructor
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L92
By default, `ALL` refactoring types are considered.

You can also call method `setRefactoringTypesToConsider(RefactoringType ... types)`
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L95-L100

Implementing this in the command-line is quite challenging as a feature, because passing the refactoring types from command-line is very error-prone, and also could make a long command if a user wants multiple refactoring types.
Perhaps having an external file to specify the refactoring types to be considered is a good idea.

For the moment the easiest think you can do is modify the list in
https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/api/RefactoringType.java#L116-L216
and re-build the tool.

I should emphasize that the tool would still detect all refactoring types, and will simply filter only the refactoring type you specified at the end.
In the way RefactoringMiner is designed, it is not possible to disable the detection of specific refactorings, as some refactorings depend on others to be detected.
So, by filtering out refactoring types, you will not see some improvement in performance.

**Comment by IP1102** [comment]
I see. Thanks for the clarification.

**Comment by IP1102** [comment]
> Duplicate with issue #244
> 
> You can comment out the refactoring types you don't want in https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/api/RefactoringType.java#L116-L216
> 
> The refactoring types to be considered is set in the GitHistoryRefactoringMinerImpl constructor https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L92 By default, `ALL` refactoring types are considered.
> 
> You can also call method `setRefactoringTypesToConsider(RefactoringType ... types)` https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L95-L100
> 
> Implementing this in the command-line is quite challenging as a feature, because passing the refactoring types from command-line is very error-prone, and could also make a long command if a user wants multiple refactoring types. Perhaps having an external file to specify the refactoring types to be considered is a good idea.
> 
> For the moment the easiest think you can do is modify the list in https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/api/RefactoringType.java#L116-L216 and re-build the tool.
> 
> I should emphasize that the tool would still detect all refactoring types, and will simply filter only the refactoring type you specified, after the end of the detection process. In the way RefactoringMiner is designed, it is not possible to disable the detection of specific refactorings, as some refactorings depend on others to be detected. So, by filtering out refactoring types, you will not see some improvement in performance.

I see, thank you so much for the clarification. Actually for my use case, I am focusing on a single type of refactoring (Extract Method) and for a large set of big repositories it's taking too much time. But I understand the problem with the current implemented architecture of the tool.

**Comment by tsantalis** [comment]
@IP1102 
Please report any commits that take too long to be processed. There might be opportunities to further improve the tool's performance.
