### ISSUE TITLE
Incorrect composite mapping within an identical pair of methods

### ISSUE THREAD

**Issue by pouryafard75** [tsantalis/RefactoringMiner#456]
**Commit**: https://github.com/bitcoinj/bitcoinj/commit/2fd96c7
**File**: [Utils.java](https://github.com/bitcoinj/bitcoinj/commit/2fd96c7#diff-aa96b381711950c54db81e49bff63c3cb11f5508c2f069c2d9d0905900922bb5)

**Problem**: The method hasn't been modified, but the `if` statements are mismapped.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/28820932/235391190-87f91a82-bcaa-40ac-a1e5-ac635c7b6aca.png">

**Comment by tsantalis** [comment]
@pouryafard75 

The issue was introduced after https://github.com/tsantalis/RefactoringMiner/commit/b283a09b5a7386bb281a8da375fc5e6fcb3c4d74 that improves support for one-to-many multi-mappings.

![Screenshot from 2023-05-01 05-54-23](https://user-images.githubusercontent.com/1483516/235438254-9f763640-b6f6-412f-a816-8c86a6cbd20e.png)
