### ISSUE TITLE
Add parameter

### ISSUE THREAD

**Issue by feifeiniu-se** [tsantalis/RefactoringMiner#504]
https://github.com/apache/commons-configuration/commit/92bf8ccdad173f1f5d4a506043d443fd0cac09a6, in this commit, I didn't see any Add Parameter refactoring, but change parameter "NamingEnumeration enum" into "Context parentContext", the original method declaration didn't exist "private recursiveGetKeys(keys List) : void".

**Comment by tsantalis** [comment]
@feifeiniu-se 
Methods `recursiveGetKeys()` and `getStartingContextPoint()` declare a variable named `enum`, which is a reserved keyword since Java 1.5

So, the parser fails to parse the body of these methods.

The way to overcome this is to set the parser with Java 1.4 compatibility
```java
Map<String, String> options = JavaCore.getOptions();
options.put(JavaCore.COMPILER_CODEGEN_TARGET_PLATFORM, JavaCore.VERSION_1_4);
options.put(JavaCore.COMPILER_SOURCE, JavaCore.VERSION_1_4);
options.put(JavaCore.COMPILER_COMPLIANCE, JavaCore.VERSION_1_4);
parser.setCompilerOptions(options);
```

However, checking whether the file contains a variable named `enum` has a computation cost, and thus I don't want to implement this check.

**Comment by tsantalis** [comment]
This is the diff of the methods.
It is clear that parameter `NamingEnumeration enum` becomes a local variable (Localize Parameter refactoring) and `Context parentContext` is an added parameter.

The same parameter `Context parentContext` is also added in method `getStartingContextPoint()`

![Screenshot from 2023-07-22 06-16-23](https://github.com/tsantalis/RefactoringMiner/assets/1483516/3c075118-8b5f-4a3f-9d47-50444ada9ae1)
![Screenshot from 2023-07-22 06-17-03](https://github.com/tsantalis/RefactoringMiner/assets/1483516/1b62c3db-6e96-4886-9d30-5c662e2cf50c)
