### ISSUE TITLE
Freezing in large commits?

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#51]
I have been noticing that, sometimes, RefactoringMiner freezes. Two examples, directly from my current study:

* https://github.com/Netflix/Hystrix/commit/d885372c6ad77a32cb0edbfd0333a0fa8bcf3285
* https://github.com/wildfly/wildfly/commit/2c84f4623c39c0b55b9db7083644b386fb474cb6

These are the last log lines from the tool:

2019-03-15 07:56:07 INFO  GitHistoryRefactoringMinerImpl:173 Processing /tmp/1552636288779-0/repo d885372c6ad77a32cb0edbfd0333a0fa8bcf3285 ...

2019-03-14 19:52:23 INFO  GitHistoryRefactoringMinerImpl:173 Processing /tmp/1552592499300-0/repo 2c84f4623c39c0b55b9db7083644b386fb474cb6 ...

The first case (2019-03-15 07:56:07), I stopped it after 2 hours. The second case (2019-03-14 19:52:23), I stopped the tool after 12 hours.

I'm running it on small droplets at DigitalOcean (1 cpu, 1gb RAM).

**Comment by tsantalis** [comment]
Thank you for reporting this issue. It seems these commits have quite large anonymous class declarations in some statements, and this slows down the comparison of these statements, because there is a large list of AST nodes being extracted to attempt node replacements.
I am trying to find a solution for this problem. It might take some time.

**Comment by tsantalis** [comment]
After the applied fixes the execution times have improved significantly:
https://github.com/wildfly/wildfly/commit/2c84f4623c39c0b55b9db7083644b386fb474cb6 takes 40 sec
https://github.com/Netflix/Hystrix/commit/d885372c6ad77a32cb0edbfd0333a0fa8bcf3285 takes 13 min
