### ISSUE TITLE
Confusion about UMLModelDiff

### ISSUE THREAD

**Issue by Laughh** [tsantalis/RefactoringMiner#518]
Hi! I'm using RMiner and I have some questions.
- Q1: the `UMLModelDiff` is equivalent to the `ASTDiff`, and `ASTDiff` is computed based on `UMLModelDiff` right? 
- Q2: `UMLOperation` is corresponding to a method ? 
- Q3: If I have instances of `ASTDiff`, is there any way to get corresponding JDT or UML element, or I have to overwrite some methods to set metadata map?

**Comment by tsantalis** [comment]
Hi @Laughh 

Thank you for your interest to our project. I will try my best to answer your questions.

**Q1**: `UMLModelDiff` stores the results of the commit diff in RMiner objects and different refactoring types.
`ASTDiff` is 100% compatible with the GumTree APIs. As you can see `ASTDiff` extends the GumTree `Diff` class.

So, to answer your question, `UMLModelDiff` corresponds to a `Set<ASTDiff>`, where each `ASTDiff` includes the mappings between a pair of matched Java files.
Please note that because RMiner supports the detection of moved code between different files, some of the mappings in an `ASTDiff` may have their left side or right side in another file.

**Q2**: UMLOperation is indeed a method.

**Q3**: As I explained in Q1 `ASTDiff` is compatible with GumTree [Diff](https://github.com/GumTreeDiff/gumtree/blob/main/core/src/main/java/com/github/gumtreediff/actions/Diff.java).

The `Diff` class includes the `TreeContext` from the left and right side, the mappings, and the editScript to transform one AST to the other.

You can have a look how we use it to generate our commit-level diff at [ProjectASTDiffer](https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/astDiff/matchers/ProjectASTDiffer.java).

@pouryafard75 can help you with more details if you have more questions.

Thank you,
Nikos

**Comment by Laughh** [comment]
Thank you for your detailed explanation! To better utilize RMiner, I have to bother you with some questions.

**Q1**: I find that the previous step is to generate `UMLModelDiff`, which contains detailed code change information, so what's the purpose to generate `ASTDiff`? For better visualization of diff result? 

**Q2**: Why `UMLOperationBodyMapper` needs a field named `parentMapper`? And can I regard `UMLOpetaionBodyMapper` as two matched methods in a same class? And why the type of field `container1` and `container2` are both `VariableDeclarationContainer`, instead of `UMLOperation`?

**Q3**: An `ASTDiff` is corresponding to a `UMLClassDiff` right? 

**Q4**: Is there any API to get the method signature of the `UMLOperation` object as declared in the source code? 

**Q5**: Why in the following code, the function `solve()` can not be matched?

<img width="1075" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/88264468/7f4352f7-480a-4b27-b873-25b023140906">

**Comment by tsantalis** [comment]
@Laughh 

This is the diff got **Q5**. Method `solve()` is properly matched.
How did you get that `solve()` is added?

![Screenshot from 2023-08-14 22-57-27](https://github.com/tsantalis/RefactoringMiner/assets/1483516/0c294f42-34bd-4406-9ad6-4c18bc72105b)

**Comment by tsantalis** [comment]
@Laughh 

Can you please give me more background about what you are trying to achieve with RefactoringMiner AST diff?

**Comment by Laughh** [comment]
> @Laughh
> 
> This is the diff got **Q5**. Method `solve()` is properly matched. How did you get that `solve()` is added?
> 
> ![Screenshot from 2023-08-14 22-57-27](https://user-images.githubusercontent.com/1483516/260616485-0c294f42-34bd-4406-9ad6-4c18bc72105b.png)

I got this in [GitHistoryRefactoringMinerImpl](https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L625) by adding output statements, like this:

<img width="1040" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/88264468/aa1d1259-9544-472f-8026-f04b54d38aed">

And here is the console output. 

<img width="607" alt="image" src="https://github.com/tsantalis/RefactoringMiner/assets/88264468/2b4a8b6b-fee8-42b8-87c9-985ba7ac1637">

**Comment by Laughh** [comment]
> @Laughh
> 
> Can you please give me more background about what you are trying to achieve with RefactoringMiner AST diff?
> 
> Regarding you other questions
> 
> **Q1**: UMLModelDiff contains information about matched classes, matched methods, matched attributes, etc. and refactorings. ASTDiff is actually an Abstract Syntax Tree diff. So, we use information from the UMLModelDiff to generate the ASTDiff, but these are two totally different things.
> 
> **Q2**: A Mapper has a `parentMapper` only in the case of Extract Method or Inline Method refactorings. In that case the `parentMapper` corresponds to the method pairs from which the method was extracted, or to which the method was inlined. `UMLOperationBodyMapper` is used to match anything that has a body. These are all subclasses of `VariableDeclarationContainer`, which can be a method, initializer block, lambda expression body, and attribute initializer with lambda expression body. `UMLOperationBodyMapper` is not only used to match local methods, but also moved methods between different files.
> 
> **Q3**: `ASTDiff` is the diff of a CompilationUnit (Java file). If a file has many classes declared inside it (i.e., inner classes), then the ASTDiff corresponds to multiple `UMLClassDiff`s
> 
> **Q4**: No, but you can add your own method in `UMLOperation` to generate the signature as you like. Currently, `toString()` generates a UML-like signature, such as `public solve(a int, b int) : void`

I wanna to get all matched classes, fields and  method, and then do my own analysis.  
Thanks for your patient replies again!

**Comment by tsantalis** [comment]
> > @Laughh
> > This is the diff got **Q5**. Method `solve()` is properly matched. How did you get that `solve()` is added?
> > ![Screenshot from 2023-08-14 22-57-27](https://user-images.githubusercontent.com/1483516/260616485-0c294f42-34bd-4406-9ad6-4c18bc72105b.png)
> 
> I got this in [GitHistoryRefactoringMinerImpl](https://github.com/tsantalis/RefactoringMiner/blob/master/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java#L632) by adding output statements, like this:
> 
> ```
> .....
> UMLModel parentUMLModel = createModel(fileContentsBefore, repositoryDirectoriesBefore);
> UMLModel currentUMLModel = createModel(fileContentsCurrent, repositoryDirectoriesCurrent);
> UMLModelDiff modelDiff = parentUMLModel.diff(currentUMLModel);
> 
> 
> for (UMLClassDiff diff : modelDiff.getCommonClassDiffList()) {
> System.out.println(diff);
> }
> .....
> ```
> 
> And here is the console output.
> <img alt="image" width="607" src="https://user-images.githubusercontent.com/88264468/260621822-2b4a8b6b-fee8-42b8-87c9-985ba7ac1637.png">

The `toString()` of UMLXXXDiff objects is only used internally in the project for debugging purposes, and should not be used to interpret the changes.
The `->` shows matched elements
`public solve(a int, b int) : void -> public solve(a int, b int) : void`
So, eventually you can see that the tool matched the methods, but initially the methods were introduced to the tool as deleted/added, because one of them does not have any code in its body.

To get the matched methods, you can use `List<UMLOperationBodyMapper> getOperationBodyMapperList()`
and then call on each Mapper `getContainer1()` and `getContainer2()`
This list also includes pairs of initializer blocks that were matched in the class.

To get the matched attributes, you can use the following methods:
```java
public List<UMLAttributeDiff> getAttributeDiffList() {
  return attributeDiffList;
}

public Set<Pair<UMLAttribute, UMLAttribute>> getCommonAtrributes() {
  return commonAtrributes;
}

public List<UMLEnumConstantDiff> getEnumConstantDiffList() {
  return enumConstantDiffList;
}

public Set<Pair<UMLEnumConstant, UMLEnumConstant>> getCommonEnumConstants() {
  return commonEnumConstants;
}
```

**Comment by tsantalis** [comment]
The `toString()` I get when I debug the code has it only once.

```
project.org.C:
operation public add() : void removed
operation public solve(a int, b int) : void removed
operation public solve(a int, b int) : void added
public main(args String[]) : void -> public main(args String[]) : void
public solve(a int, b int) : void -> public solve(a int, b int) : void
```
![Screenshot from 2023-08-15 08-04-59](https://github.com/tsantalis/RefactoringMiner/assets/1483516/ee955b68-c52d-41d0-9fff-21d7fe0ca42f)

Also it seems to me, you call the diff in the reverse way (from right to left), because `add()` method is removed, but in your log appears as added.
The `diff()` method should be called on the leftModel.
`leftModel.diff(rightModel)`
and obviously the diff is directed
`rightModel.diff(leftModel)`
produces the reverse results.

When I reverse the diff, again `solve()` appears only once
```
project.org.C:
operation public solve(a int, b int) : void removed
operation public add() : void added
operation public solve(a int, b int) : void added
public main(args String[]) : void -> public main(args String[]) : void
public solve(a int, b int) : void -> public solve(a int, b int) : void
```

**Comment by tsantalis** [comment]
> > 
> So the `addedOperation` doesn't mean the added methods in the next class right? But if I need added or removed methods, what should I do?
> 

The reason `solve()` is kept in the removed/added methods is because in one of the sides, it has an empty body.
So, for this reason, we want to check at commit-level if this method has been pulled up to a superclass or pushed down to a subclass.
Developers in some cases move a method in the hierarchy, but keep an empty (default) implementation in the original class. We wanted to cover this scenario.

If you add any code inside the empty `solve()`, the the diff output becomes:
```
project.org.C:
operation public add() : void removed
public main(args String[]) : void -> public main(args String[]) : void
public solve(a int, b int) : void -> public solve(a int, b int) : void
```

**Comment by Laughh** [comment]
> 

Sorry, I reversed the screenshot, where the right source code is corresponding to original class. And I had a wrong description, `public solve(a int, b int): void -> public solve(a int, b int): void` appeared **twice** when I call `toString()` for each Mapper of `List<UMLOperationBodyMapper> getOperationBodyMapperList()`.

As the scenario you described, if I wanna get added/removed methods, I should remove the methods both in `addedOperationList` and `removeOperationList`, right? Or removed matched methods from all declaring methods in original and next class?

**Comment by tsantalis** [comment]
@Laughh 
A method is actually added, if it is present in `addedOperationList` and there is no mapper in `getOperationBodyMapperList()` having it as `container2`

A method is actually deleted, if it is present in `removedOperationList` and there is no mapper in `getOperationBodyMapperList()` having it as `container1`

**Comment by Laughh** [comment]
> @Laughh A method is actually added, if it is present in `addedOperationList` and there is no mapper in `getOperationBodyMapperList()` having it as `container2`
> 
> A method is actually deleted, if it is present in `removedOperationList` and there is no mapper in `getOperationBodyMapperList()` having it as `container1`

Thank you very much for your reply.
