### ISSUE TITLE
Freezing for days

### ISSUE THREAD

**Issue by evertonrenne** [tsantalis/RefactoringMiner#52]
Hello,
I'm trying to execute RefactoringMiner between tags of https://github.com/ccrama/Slide and the process still running for days without finish.

Any ideas?

RefactoringMiner/bin/RefactoringMiner -bt /Users/dontbr/ufpe/repositories/tmp/Slide 4.3.1 4.4.2

**Comment by tsantalis** [comment]
https://github.com/ccrama/Slide/commit/dbf9527b742a806bcc15642705f755574aca2ff2 is very slowly processed.

**Comment by tsantalis** [comment]
@evertonrenne Please update to the latest commit.
https://github.com/ccrama/Slide/commit/dbf9527b742a806bcc15642705f755574aca2ff2 should take around 10 minutes to be processed.
This particular commit has many array creations with an initializer having a long list of expressions.
The comparison of these statements was taking long, because there was a very large number of replacement combinations to be performed in order to match the statements.
