### ISSUE TITLE
Provide lines added/removed per refactoring

### ISSUE THREAD

**Issue by jazzmuesli** [tsantalis/RefactoringMiner#57]
Dear Nikolaos,

Thanks for the amazing tool! I'd like to use it to calculate the proportion of lines changed caused by refactorings. Sometimes developers use dedicated commits for refactoring and often refactor in the same commit with production/test code changes.

For example, in this commit https://github.com/jazzmuesli/tauksi/commit/e6770421ac6f24f47581b00d4d07b38ba9c5b348 I've extracted a method and in total added 5 lines, all of them can be explained by this refactoring.
I can extract 7 CodeRange of the refactoring, 2 on the left and 5 on the right - but I can't deduce much from startLine/endLine. 
![image](https://user-images.githubusercontent.com/2883793/60849434-93735200-a1e2-11e9-8398-7597d03031f9.png)

There is Churn class https://github.com/tsantalis/RefactoringMiner/blob/8326323c7473f23aab669130f35692a49e89a9ee/src/org/refactoringminer/rm1/GitHistoryRefactoringMinerImpl.java, but I think it would merely provide a number of lines added/removed for the entire commit, without taking into account refactorings.

I know RefactoringMiner uses UMLModel and is therefore quite detached from lines of code - but could you suggest any pointers?

Thanks.

**Comment by tsantalis** [comment]
Hi @jazzmuesli 

Your feature request is quite challenging, because different people might have different opinions about what are the actual lines of code changed by a refactoring.

In your example, the textual diff gives 6 lines added and 1 deleted.

The truly added code is line 22 on the right (return statement in the extracted method),
line 7 on the right (call to the extracted method), and line 11 on the right (extracted method signature).
This means 3 lines added and 0 deleted.

Someone could argue that the refactoring did not introduce any new lines of code,
because all aforementioned added lines are part of the refactoring mechanics.

I agree with you (and we have empirical evidence) that developers apply refactorings along with other maintenance tasks, such as bug fixes and feature implementations.
This is why RefactoringMiner provides also the added statements in the extracted method and the deleted statements in the source method.
These statements might correspond to a a bug fix or a new feature.

In any case, the CodeRange objects provided for each refactoring can actually help to implement your own algorithm computing how many lines were added/deleted/changed in a refactored code.
But it is very tricky (and it is actually an open research problem) to distinguish the code being part of a refactoring and the code being part of another maintenance tasks that overlaps with the refactored code.
