### ISSUE TITLE
Getting fully qualified signature of a method

### ISSUE THREAD

**Issue by jzheng2017** [tsantalis/RefactoringMiner#668]
Is there a way to get the fully qualified signature of a method that has been refactored (e.g. RenameOperationRefactoring)? Currently I can derive the path to the class with `className` and the function name with `name` however the issue then are the arguments as only non qualified class names are provided. So for example I can only derive `org.example.Class.function(String, someCustomClass)` but I want `org.example.Class.function(java.lang.String, org.example.someCustomClass)`

**Comment by tsantalis** [comment]
`UMLOperation.toQualifiedString()` returns qualified parameter types, but only if they are qualified in the actual source code.

In order to qualify the non-qualified parameter types, we need to perform type inference, meaning that we need to match the non-qualified parameter types with the corresponding import declarations of the file.
This is a feature that is not currently available, but it could be implemented.
