### ISSUE TITLE
Added Java comment should be shown

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#749]
Context: https://github.com/JabRef/jabref/pull/11399

GitHub:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/6aa2432c-8cd1-4454-a4ac-a7c6e3ed2993)

RefactoringMiner:

![image](https://github.com/tsantalis/RefactoringMiner/assets/1366654/f907b78a-2f1d-403f-a0e3-30ef3a639282)

**Comment by tsantalis** [comment]
@koppor 
Thank you for reporting this issue.

This is actually an inline comment, not Javadoc.

The reason I make this distinction is because the Eclipse JDT Parser we use, represent Javadoc as AST nodes, but inline comments are not represented as AST nodes.
This makes it impossible for us to show any changes for inline comments.

I will discuss with @pouryafard75 if there is any way to solve this issue.

**Comment by tsantalis** [comment]
@koppor @pouryafard75 
Once this [PR](https://github.com/GumTreeDiff/gumtree/pull/368) get merged, we will be able to support inline comment diff.

**Comment by tsantalis** [comment]
@pouryafard75 
PR merged.

**Comment by pouryafard75** [comment]
@tsantalis 
I beleive they have a CI pipeline for publishing to maven central. So as soon as new release get published in maven, we migrate to it. If they dont publish a new release, I will find a workaround for it.

**Comment by pouryafard75** [comment]
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/1c787cff-3779-466b-b19a-e94a239bddf0">

@koppor @tsantalis

**Comment by tsantalis** [comment]
@koppor 
Comment diff is still under development.
If you see anything strange related to comments, please report it to us.
I will close this issue, as it is fixed. We have created a new issue #785 related to comments.
