### ISSUE TITLE
Strange diff

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#766]
Context: https://github.com/JabRef/jabref/pull/11542/files --> `src/main/java/org/jabref/gui/entryeditor/fileannotationtab/FulltextSearchResultsTab.java`

I would not expect "everything" red and green - there are many similar code fragments:

![image](https://github.com/user-attachments/assets/90aa7ce7-2434-4baf-9141-ea112690dd8f)

Is it possible to adjust the matching while browsing? Say: Hey, dear tool, please a lower threshold for finding matches - I would like to see more similar lines and just see the differences?

**Comment by tsantalis** [comment]
@koppor 

I am working on this issue. I also spotted this one.
The problem is that the number of lambdas is different in the two sides, and the tool is not processing them.

I already made some improvement in
https://github.com/tsantalis/RefactoringMiner/issues/765#issuecomment-2316035459
but we can do better than that.

**Comment by tsantalis** [comment]
@koppor 

This is the optimal diff for this change.

![Screenshot from 2024-08-28 15-48-35](https://github.com/user-attachments/assets/2320332a-c2a7-4060-82f0-c25d3833aaba)
