### ISSUE TITLE
Wrong Parameterize Attribute

### ISSUE THREAD

**Issue by l123zy** [tsantalis/RefactoringMiner#779]
I am using a tool to perform refactoring detection between two code repositories. The detected result shows that a 'Parameterize Attribute' type refactoring has occurred
![3](https://github.com/user-attachments/assets/1513e526-e8b2-425d-9d3b-ef47c6b59740)
, but in fact, the method on line 101
![2](https://github.com/user-attachments/assets/abbe3c17-7220-425a-8628-579238c585ea)
 of the downstream code is a new method and not a transformation of the attribute on line 61 
![1](https://github.com/user-attachments/assets/6ffd86b2-5a80-4d8b-9cd2-e9baeb1c7a53)
of the upstream code into a parameter of this method. How can this issue be resolved?

**Comment by tsantalis** [comment]
@l123zy 
Could you please provide the commit URL for this case?

**Comment by l123zy** [comment]
This is the upstream URL: https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r61/media/tests/MtpTests/src/android/mtp/MtpStorageManagerTest.java

This is the downstream refactored URL: https://github.com/LineageOS/android_frameworks_base/blob/lineage-16.0/media/tests/MtpTests/src/android/mtp/MtpStorageManagerTest.java

**Comment by tsantalis** [comment]
Hello @l123zy 
I examined the AST diff generated by our tool.
There is a newly extracted method `private createNewFileNonZero(parent File, name String)`, which is extracted from multiple tests.

```java
private static File createNewFileNonZero(File parent) {
        return createNewFileNonZero(parent, "file-" + UUID.randomUUID().toString());
}

private static File createNewFileNonZero(File parent, String name) {
        return createNewFile(parent, name, true);
}
```

In all call sites, we have the following change:
`File newFile = createNewFile(mainStorageDir);` ->
`File newFile = createNewFileNonZero(mainStorageDir);`

The reported refactoring is simply saying that in the extracted method `createNewFileNonZero`
the attribute `mainStorageDir` has become the parameter `parent`.

This actually is correct, instead of using directly the attribute `mainStorageDir` the extracted method `createNewFileNonZero` introduced the parameter `parent` in order to make the method more reusable.

As you can see there are also some calls to the extracted method passing other arguments, such as `moved`
`createNewFileNonZero(moved);`
This strengthens the argument that the parameter `parent` was introduced for reusability.

Please let me know if you have a different opinion.
