### ISSUE TITLE
Add support for `@CsvSource`

### ISSUE THREAD

**Issue by koppor** [tsantalis/RefactoringMiner#790]
The PR https://github.com/JabRef/jabref/pull/12014 converted multiple `assertEquals` to `@CsvSource` and `@ParameterizedTest`

It is hard to review if all thing were made properly

RFM does not help at all here:

![image](https://github.com/user-attachments/assets/99addcd2-9b1c-4e61-9e1b-1fc59805e263)

---

I know, this is an advanced feature and might not be needed often; but it would help us very, very much to review PRs.

**Comment by tsantalis** [comment]
@koppor 
The tool actually supports this refactoring.
I will check why this case was not detected.
Thank you for your continuous feedback.

**Comment by tsantalis** [comment]
@koppor @victorgveloso 

The issue has been fixed.
We are able to establish multi-mappings, and detect the following `Parameterize Test` refactorings:

Parameterize Test	`package cleanFileName() : void` to `package cleanFileName(expected String, input String) : void` in class org.jabref.logic.util.FileNameCleanerTest
Parameterize Test	`package cleanCurlyBracesAsWell() : void` to `package cleanFileName(expected String, input String) : void` in class org.jabref.logic.util.FileNameCleanerTest
Parameterize Test	`package cleanDirectoryName() : void` to `package cleanDirectoryName(expected String, input String) : void` in class org.jabref.logic.util.FileNameCleanerTest
Parameterize Test	`package cleanDirectoryNameForWindows() : void` to `package cleanDirectoryNameForWindows(expected String, input String) : void` in class org.jabref.logic.util.FileNameCleanerTest

Please note that although the tool internally has the mappings for the parameterized arguments, the diff tool cannot show them, because string literals are getting concatenated to a larger comma-separated string literal.
I am not sure if this is fixable @pouryafard75 

![image](https://github.com/user-attachments/assets/376a8c87-7180-425c-b649-7fc6d0b8bd08)

**Comment by pouryafard75** [comment]
"@tsantalis This won't be fixed. The string literals are treated as an atomic elements in terms of granularity, so we don't break it down into sub-nodes.

**Comment by koppor** [comment]
> @tsantalis This won't be fixed. The string literals are treated as an atomic elements in terms of granularity, so we don't break it down into sub-nodes.

Thank you for the update. 😥, but I think, this is too seldomly done.
