### ISSUE TITLE
Extract variable together with a extract method (bug?)

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#82]
See what RefactoringMiner detects at https://github.com/apache/commons-csv/commit/02b21463e68e7b3d5f3d9980746d131a08a08eed

```
Process Commit [02b21463e68e7b3d5f3d9980746d131a08a08eed] Refactoring: [Extract Variable	first : boolean in method package printAndEncapsulate(value char[], offset int, len int) : void from class org.apache.commons.csv.CSVPrinter]
```

The method `printAndEncapsulate()` was introduced in this commit, and thus, maybe it makes no sense to identify an "extract variable" here.

Or am I missing something?

**Comment by tsantalis** [comment]
The current version of RefactoringMiner supports the detection of **nested** refactoring operations,
including nested Extract Method and Inline Method, in addition to low-level nested refactorings, such as Rename variable, Extract Variable, Inline Variable, etc.
The case you reported is a valid Extract Variable, based on the replacement `newLine` -> `first` taking place in the condition of the `if` statement below:
```java
if (newLine
          && (c < '0'
          || (c > '9' && c < 'A')
          || (c > 'Z' && c < 'a')
          || (c > 'z'))) {
```
```java
boolean first = newLine;  // is this the first value on this line?
if (first
          && (c < '0'
          || (c > '9' && c < 'A')
          || (c > 'Z' && c < 'a')
          || (c > 'z'))) {
```
In this commit the 3 Extract Method refactorings are actually nested, because the body of the original method `public void print(String value)` becomes after refactoring:
```java
public void print(String value) throws IOException {
    print(value, true);   
}
```
So, we have this sequence of nested Extract Method refactorings:
`print(String value)` -> `print(String value, boolean checkForEscape)` -> `print(char[] value, int offset, int len, boolean checkForEscape)` -> `printAndEncapsulate(char[] value, int offset, int len)`
A similar Extract Variable inside an extracted method can be found in commit https://github.com/JetBrains/intellij-community/commit/7ed3f273ab0caf0337c22f0b721d51829bb0c877
Another very interesting case of nested Extract Method refactorings can be found in commit https://github.com/spring-projects/spring-boot/commit/becced5f0b7bac8200df7a5706b568687b517b90
