### ISSUE TITLE
Strange Extract Superclass detected

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#89]
In commit `4af0169539667e66cff4fdd9a359a062508bb0f5` of the [Greenbits](https://github.com/greenaddress/GreenBits) project, RefactoringMiner finds a: 

```Extract Superclass com.greenaddress.greenbits.ui.preferences.GAPreferenceFragment from classes [com.greenaddress.greenbits.ui.preferences.TwoFactorPreferenceFragment]```

However, when you look at the [commit](https://github.com/greenaddress/GreenBits/commit/4af0169539667e66cff4fdd9a359a062508bb0f5), you see that the `TwoFactorPreferenceFragment` class was just introduced. How can it be the source of a _Extract Superclass_?

Am I missing something here, or is this a bug?

**Comment by tsantalis** [comment]
There are two relevant refactorings that explain what happened:
1. Move And Rename Class `com.greenaddress.greenbits.ui.SettingsActivity` moved and renamed to `com.greenaddress.greenbits.ui.preferences.TwoFactorPreferenceFragment`
2. Extract Class `com.greenaddress.greenbits.ui.preferences.SettingsActivity` from class `com.greenaddress.greenbits.ui.SettingsActivity`

I manually diffed the code using Meld, and the refactorings above are valid.

It seems that `com.greenaddress.greenbits.ui.SettingsActivity` is split into two classes:
1. `com.greenaddress.greenbits.ui.preferences.SettingsActivity`
2. `com.greenaddress.greenbits.ui.preferences.TwoFactorPreferenceFragment`

Since the tool detects `TwoFactorPreferenceFragment` is a result of moving and renaming an existing class, then the reported Extract Superclass refactoring involves an existing class.

**Comment by mauricioaniche** [comment]
That makes sense to me; I'm closing the issue. Thanks!
