### ISSUE TITLE
Incomplete type detection

### ISSUE THREAD

**Issue by mauricioaniche** [tsantalis/RefactoringMiner#91]
See this [commit](https://github.com/toly1994328/DS4Android/commit/2de1313a031155fc5c01e5af479eb3c29a7808d2), method `drawNode`.

The method signature is `drawNode(Canvas canvas, BinarySearchTree<TreeNode<E>>.Node node)`. RMiner gets it as `drawNode(canvas Canvas, node BinarySearchTree<TreeNode<E>>)`. Note the `.Node` at the end is missing.

**Comment by ameyaKetkar** [comment]
We can blame this [line](https://github.com/tsantalis/RefactoringMiner/blob/57c8b5f783ee5d124cae2b9453f48c5520ef3eff/src/gr/uom/java/xmi/UMLType.java#L235) for the bug because it assigns `qualifiedName` to `qualifiedName(substring(0, indexOf("<")))`, and this `qualifiedName` to `UMLType` [here](https://github.com/tsantalis/RefactoringMiner/blob/57c8b5f783ee5d124cae2b9453f48c5520ef3eff/src/gr/uom/java/xmi/UMLType.java#L238). 
I think `UMLType` creation should be more syntax aware (rather than manipulating strings)
